export const siteConfig = {
  name: "Aeroven Global IT Solutions",
  shortName: "Aeroven",
  tagline: "Designing and building AI-powered, scalable solutions.",
  description:
    "Aeroven Global IT Solutions designs and builds AI-powered, scalable digital platforms for startups and enterprises — custom software, cloud, data, and applied AI.",
  url: process.env.NEXT_PUBLIC_SITE_URL?.replace(/\/$/, "") || "https://aeroven.com",
  locale: "en_US",
  email: "hello@aeroven.com",
  phone: "+1 (415) 555-0199",
  address: {
    street: "525 Market St, Suite 2200",
    city: "San Francisco",
    region: "CA",
    postalCode: "94105",
    country: "US",
  },
  social: {
    LinkedIn: "https://www.linkedin.com/company/aeroven-global-it",
    X: "https://x.com/aeroven",
    GitHub: "https://github.com/aeroven",
    YouTube: "https://www.youtube.com/@aeroven",
  },
} as const;

/** Canonical internal routes used across nav, footer, and SEO */
export const routes = {
  home: "/",
  about: "/about",
  capabilities: "/capabilities",
  process: "/process",
  engagement: "/engagement",
  success: "/success",
  careers: "/careers",
  consultation: "/consultation",
  contact: "/consultation",
  newsroom: "/newsroom",
  blog: "/blog",
  docs: "/docs",
  support: "/support",
  privacy: "/privacy",
  terms: "/terms",
  cookies: "/cookies",
  caseStudies: "/success",
} as const;

export const footerLinks: Record<string, string> = {
  About: routes.about,
  Careers: routes.careers,
  Newsroom: routes.newsroom,
  Contact: routes.contact,
  "AI Engineering": `${routes.capabilities}#data-applied-ai`,
  Cloud: `${routes.capabilities}#cloud-devops`,
  Data: `${routes.capabilities}#data-applied-ai`,
  Strategy: routes.engagement,
  "Digital Transformation": `${routes.capabilities}#digital-transformation`,
  "Cloud & DevOps": `${routes.capabilities}#cloud-devops`,
  "Data & Applied AI": `${routes.capabilities}#data-applied-ai`,
  "Quality & Security": `${routes.capabilities}#quality-security`,
  Capabilities: routes.capabilities,
  Process: routes.process,
  Engagement: routes.engagement,
  Success: routes.success,
  "Case Studies": routes.caseStudies,
  Blog: routes.blog,
  Docs: routes.docs,
  Support: routes.support,
  "Privacy Policy": routes.privacy,
  "Terms of Service": routes.terms,
  Cookies: routes.cookies,
};

export const allMarketingPaths = [
  routes.home,
  routes.about,
  routes.capabilities,
  routes.process,
  routes.engagement,
  routes.success,
  routes.careers,
  routes.consultation,
  routes.newsroom,
  routes.blog,
  routes.docs,
  routes.support,
  routes.privacy,
  routes.terms,
  routes.cookies,
] as const;
